exports.data = {
  level1: {
    nodeDataArr: [
      { id: 0, text: "Patel Family", color: "white", loc: "0 50" },
      { id: 1, text: "Nilesh", color: "white", loc: "150 0" },
      { id: 2, text: "Geeta", color: "white", loc: "150 50" },
      { id: 3, text: "Jainam", color: "white", loc: "150 100" },
    ],
    linkDataArr: [
      { key: -1, from: 0, to: 1 },
      { key: -2, from: 0, to: 2 },
      { key: -3, from: 0, to: 3 },
    ],
  },
  level2_id1: {
    nodeDataArr: [
      { id: 0, text: "Nilesh Patel", color: "white", loc: "0 70" },
      { id: 1, text: "Father", color: "white", loc: "150 0" },
      { id: 2, text: "Mother", color: "white", loc: "150 50" },
      { id: 3, text: "Wife", color: "white", loc: "150 100" },
      { id: 4, text: "BOD", color: "white", loc: "150 150" },
      { id: 5, text: "Suryakant Patel", color: "white", loc: "300 0" },
      { id: 6, text: "Vansti Patel", color: "white", loc: "300 50" },
      { id: 7, text: "Geeta Patel", color: "white", loc: "300 100" },
      { id: 8, text: "05/03/1975", color: "white", loc: "300 150" },
    ],
    linkDataArr: [
      { key: -1, from: 0, to: 1 },
      { key: -2, from: 0, to: 2 },
      { key: -3, from: 0, to: 3 },
      { key: -4, from: 0, to: 4 },
      { key: -5, from: 1, to: 5 },
      { key: -6, from: 2, to: 6 },
      { key: -7, from: 3, to: 7 },
      { key: -8, from: 4, to: 8 },
    ],
  },
  level2_id2: {
    nodeDataArr: [
      { id: 0, text: "Geeta Patel", color: "white", loc: "0 70" },
      { id: 1, text: "Father", color: "white", loc: "150 0" },
      { id: 2, text: "Mother", color: "white", loc: "150 50" },
      { id: 3, text: "Husband", color: "white", loc: "150 100" },
      { id: 4, text: "BOD", color: "white", loc: "150 150" },
      { id: 5, text: "Mafat Patel", color: "white", loc: "300 0" },
      { id: 6, text: "Narabda Patel", color: "white", loc: "300 50" },
      { id: 7, text: "Nilesh Patel", color: "white", loc: "300 100" },
      { id: 8, text: "10/03/1976", color: "white", loc: "300 150" },
    ],
    linkDataArr: [
      { key: -1, from: 0, to: 1 },
      { key: -2, from: 0, to: 2 },
      { key: -3, from: 0, to: 3 },
      { key: -4, from: 0, to: 4 },
      { key: -5, from: 1, to: 5 },
      { key: -6, from: 2, to: 6 },
      { key: -7, from: 3, to: 7 },
      { key: -8, from: 4, to: 8 },
    ],
  },
  level2_id3: {
    nodeDataArr: [
      { id: 0, text: "Jainam Patel", color: "white", loc: "0 70" },
      { id: 1, text: "Father", color: "white", loc: "150 0" },
      { id: 2, text: "Mother", color: "white", loc: "150 50" },
      { id: 4, text: "BOD", color: "white", loc: "150 150" },
      { id: 5, text: "Nilesh Patel", color: "white", loc: "300 0" },
      { id: 6, text: "Geeta Patel", color: "white", loc: "300 50" },
      { id: 8, text: "25/01/2001", color: "white", loc: "300 150" },
    ],
    linkDataArr: [
      { key: -1, from: 0, to: 1 },
      { key: -2, from: 0, to: 2 },
      { key: -4, from: 0, to: 4 },
      { key: -5, from: 1, to: 5 },
      { key: -6, from: 2, to: 6 },
      { key: -8, from: 4, to: 8 },
    ],
  },
};
